### ISSUE TITLE
Site's new DDOS-GUARD DDOS protection is resulting in errors when scraping

### ISSUE THREAD

**Issue by kenneththerodgers** [MillenniumEarl/F95API#267]
I see this when running the example with the correct credentials. I can confirm that this worked a few days ago when was testing #257. Pretty sure this is caused by the newly added DDOS protection from [DDOS-GUARD](https://ddos-guard.net/). Need to debug this further and probably look into bypassing DDOS-GUARD (could be something custom or a lib).

f95api: `v2.0.0-beta.12`
Node.js: `v17.6.0`
Windows 10: `v19044.1586`
```
PS G:\dev\code\F95API> npm run example

> @millenniumearl/f95api@2.0.0-beta.12 example     
> npm run build && node --inspect ./dist/example.js


> @millenniumearl/f95api@2.0.0-beta.12 prebuild
> node -p "'export const LIB_VERSION = ' + JSON.stringify(require('./package.json').version) + ';'" > src/version.ts


> @millenniumearl/f95api@2.0.0-beta.12 build
> npm run prebuild && tsc --project ./      


> @millenniumearl/f95api@2.0.0-beta.12 prebuild
> node -p "'export const LIB_VERSION = ' + JSON.stringify(require('./package.json').version) + ';'" > src/version.ts

Debugger listening on ws://127.0.0.1:9229/cedbfbf7-6837-4df6-ba8e-3fb0e50b85d3
For help, see: https://nodejs.org/en/docs/inspector
Authenticating...
G:\dev\code\F95API\dist\scripts\network-helper.js:111
        throw new errors_1.InvalidF95Token(`Invalid token for auth: ${credentials.token}`);
              ^

InvalidF95Token [Error]: Invalid token for auth: undefined
    at authenticate (G:\dev\code\F95API\dist\scripts\network-helper.js:111:15)        
    at loginInTheRemotePlatform (G:\dev\code\F95API\dist\scripts\login.js:105:58)     
    at login (G:\dev\code\F95API\dist\scripts\login.js:47:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async authenticate (G:\dev\code\F95API\dist\example.js:72:20)
    at async main (G:\dev\code\F95API\dist\example.js:143:9)
```

**Comment by kenneththerodgers** [comment]
https://f95zone.to/threads/changed-something-to-the-ddos-protection-configuration.106539/

**Comment by kenneththerodgers** [comment]
Something like this could be helpful - https://www.npmjs.com/package/ddos-guard-bypass.

**Comment by MillenniumEarl** [comment]
Thanks for the report, I will try to find a solution as soon as possible!

**Comment by MillenniumEarl** [comment]
Support added and everything seems to work fine in v.2.0.0-beta.13

**Comment by kenneththerodgers** [comment]
Thank you! Can confirm it works on my end as well.
